---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: group-ctf-de
commonLabels:
    app.kubernetes.io/part-of: group-ctf-de
commonAnnotations:
    app.kubernetes.io/repository: "https://github.com/timonegk/group-ctf.de"

resources:
    - k8s/namespace.yml
    - k8s/deployment.yml
    - k8s/service.yml

