---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-ctf-de
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: webserver
      app.kubernetes.io/name: group-ctf-de-website
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webserver
        app.kubernetes.io/name: group-ctf-de-website
    spec:
      containers:
        - name: server
          image: registry.finn-thorben.me/ftsell/group-ctf-de
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              port: http
              path: /
          livenessProbe:
            httpGet:
              port: http
              path: /
