---
apiVersion: v1
kind: Service
metadata:
  name: group-ctf-de
  labels:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: group-ctf-de-website
spec:
  selector:
    app.kubernetes.io/component: webserver
    app.kubernetes.io/name: group-ctf-de-website
  ports:
    - name: http
      port: 80
      targetPort: http
